/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ExtendedTable;
import java.math.*;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Ahsan
 */
public class StandardDeviation extends javax.swing.JFrame {

    /**
     * Creates new form StandardDeviation
     */
    public StandardDeviation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel6.setText("Standard Deviation");

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(30);
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel3.setText("Mean");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel4.setText("Mean");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel5.setText("Mean");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel7.setText("Mean");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(128, 128, 128))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StandardDeviation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StandardDeviation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StandardDeviation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StandardDeviation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StandardDeviation().setVisible(true);
            }
        });
    }
    
        
    //********************* MY CODE ********************
    
    Double limits[][];
    Integer frequency[];
    Double midPoint[];
    BigDecimal fX[];
    BigDecimal mean;
    BigDecimal x_xbar[];
    BigDecimal x_xbarsquare[];
    BigDecimal fx_xbarsquare[];
    
    StandardDeviation(Double[][] limits, Integer[] frequency, Double[] midPoint){
        
        this();
        
        setResizable(false);
        
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        
        this.limits = limits;
        this.frequency = frequency;
        this.midPoint = midPoint;
        
        fX = new BigDecimal[frequency.length];
        //mean = new BigDecimal("");
        x_xbar = new BigDecimal[frequency.length];
        x_xbarsquare = new BigDecimal[frequency.length];
        fx_xbarsquare = new BigDecimal[frequency.length];
        
        computeFX();
        computexbar();
        computex_xbar();
        computex_xbarsquare ();
        computefx_xbarsqaure();
        
        jLabel3.setText(new String("x\u0305 = (\u03A3 F*X) / n = " + sum(fX) + " / " + sum(frequency) + " \u2248 " + (Double.parseDouble(sum(fX)) / sum(frequency))));
        
        jLabel4.setText("S.D = \u221A( F(x - x\u0305 ) ^ 2 / n )");
        
        jLabel5.setText("S.D = %s / %s".formatted(sum(fx_xbarsquare).substring(0, 10), sum(frequency)));
        
        jLabel7.setText("S.D = %f".formatted(Math.sqrt(Double.parseDouble(sum(fx_xbarsquare).substring(0, 10)) / (sum(frequency)))));
        
        // Initialize Table
        
           String data[][] = new String[frequency.length + 1][7];
           
           for (int i = 0; i < frequency.length; i++) {

		data[i][0] = limits[0][i] + "-" + limits[1][i];
		data[i][1] = "" + frequency[i];
                data[i][2] = "" + midPoint[i];
                data[i][3] = "" + fX[i];
                data[i][4] = "" + x_xbar[i];
                data[i][5] = "" + x_xbarsquare[i];
                data[i][6] = "" + fx_xbarsquare[i];
           }
           
           data[frequency.length][0] = "Sum";
           data[frequency.length][1] = "" + sum(frequency);
           data[frequency.length][3] = sum(fX);
           data[frequency.length][6] = sum(fx_xbarsquare);
           
           String column[] = { "Class Intevals", "F","Mid Points X", "F*X", "x - x\u0305", "( x - x\u0305)2", "F*(|x - x\u0305|)2" };
           jTable1.setModel(new javax.swing.table.DefaultTableModel(data,column));
           
           TableColumnModel columnModel = jTable1.getColumnModel();   
           
           columnModel.getColumn(0).setPreferredWidth(45);
           columnModel.getColumn(1).setPreferredWidth(20);
           columnModel.getColumn(2).setPreferredWidth(30);
           columnModel.getColumn(3).setPreferredWidth(30);
           columnModel.getColumn(4).setPreferredWidth(30);
        
    }
    
    void computeFX(){
    
        for(int i = 0; i < fX.length; i++){
        
            fX[i] = new BigDecimal("" + (midPoint[i] * frequency[i]));
        }
    }
    
    String sum(BigDecimal data[]){
    
        BigDecimal sum = new BigDecimal("0");

        for(int i = 0; i < data.length;i++){
        
            sum = sum.add(data[i]);
        }
        
        return sum.toString();
    }
    
    int sum(Integer data[]){
    
         Integer sum = 0;

        for(int i = 0; i < data.length;i++){
        
            sum += data[i];
        }
        
        return sum;
    }
    
    void computexbar(){ // Mean
    
        mean = new BigDecimal("" + Double.parseDouble(sum(fX)) / sum(frequency));
    
    }
    
    void computex_xbar(){
        
        for(int i = 0; i < x_xbar.length; i++){
        
            x_xbar[i] = new BigDecimal((midPoint[i] - mean.doubleValue()) + "");
            
        }
    }
    
    void computex_xbarsquare(){
        
         for(int i = 0; i < x_xbarsquare.length; i++){
              x_xbarsquare[i] = x_xbar[i].multiply(x_xbar[i]);
         }
    }
    
    void computefx_xbarsqaure(){
    
        for(int i = 0; i < frequency.length; i++){    
        
            fx_xbarsquare[i] = x_xbarsquare[i].abs().multiply(new BigDecimal(frequency[i] + ""));
        }
    }
    //********************* MYY CODE *******************

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}